### ISSUE TITLE
Update glob tag for data

### ISSUE THREAD

**Issue by l-cadamuro** [LLRCMS/LLRHiggsTauTau#27]
From here: https://twiki.cern.ch/twiki/bin/view/Main/GlobalTags

    process.load("Configuration.StandardSequences.FrontierConditions_GlobalTag_condDBv2_cff")
    # New Tag format for 2015, also ::All no longer required 
    Tag = '74X_dataRun2_Prompt_v1'

**Comment by giacomoortona** [comment]
They are claiming ::All is not needed anymore since a while, but the first times they did this claim it wasn't true. Let's check it before changing it
