### ISSUE TITLE
Enable possibility to use NoHFMET instead of normal PF MET

### ISSUE THREAD

**Issue by l-cadamuro** [LLRCMS/LLRHiggsTauTau#29]
Needed to run on Silver json. Of course this MET must also be used as input for the SVfit computation.

**Comment by salerno** [comment]
MET to be used: 
slimmedMETsNoHF

**Comment by l-cadamuro** [comment]
The type of PF met (HF / noHF) can be decided with a switch in analyzer.py and it will be used for both SVfit and met, metphi branches in output ntuple
