### ISSUE TITLE
Updates before MC reprocessing

### ISSUE THREAD

**Issue by l-cadamuro** [LLRCMS/LLRHiggsTauTau#57]
+ Update the globaltag before processing Moriond17 MC.
Globaltag list is here:
https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideFrontierConditions#Global_Tags_for_PdmVMCcampaignRu

+ Update electron MVA ID to the latest POG recipe: https://hypernews.cern.ch/HyperNews/CMS/get/higgs2e2nu/733.html

+ Update JEC (probably will be available before Christmas)

+ Update tau MVA ID as soon as the Tau POG completes the re-training on the latest MC samples

**Comment by francescobrivio** [comment]
I believe this can be closed, @l-cadamuro ? :)

**Comment by l-cadamuro** [comment]
Hi Fra, yeah definitely :-)
