### ISSUE TITLE
Variables

### ISSUE THREAD

**Issue by giacomoortona** [LLRCMS/LLRHiggsTauTau#6]
We need to include all the needed variables. Here is a temptative list:
Leptons:
-mothers/daughters 4-momenta (DONE)
-referencing mother/daughter (DONE)
-pdg (DONE)
-lepton quality?
e/mu/taus single collections (for vetos) (DONE)
 
JET:
- all jet 4-momenta (DONE)
- b tagging CSV score value (DONE)
- number of jets (DONE)
- number of jets b tagged  (or we save all jets?)=>(DONE, save all)

TAUH: (DONE)
- ISO tauh (tightestHPSMVA3oldDMwLTWP (DONE)
- decay mode from HPS algorithm (DONE)

MET: 
- METMag
- METPhi
- ...

OTHER:
-eventnumber (DONE)
-run (DONE)
-trigger bit (DONE)
- flags veto on additional e/mu/tauh ? Or we leave it to analysis? (DONE=> leave to analysis)
- SVFitMass (this belongs to another issue)

**Comment by giacomoortona** [comment]
Added:
Gen Leptons (all)
b quarks (only b, not decay products)

Still to be done:
gen Jets
gen tau decay products

**Comment by giacomoortona** [comment]
Requests from Cécile
- pileup jet ID
- jet ID (maybe not needed)
- trigger objects or trigger matching
- met filters (maybe not needed)
- lumi (lumisection?)
- if the last filter of the trigger path has been fired (?)
- generated top pT for top quark pT reweighting
- generated Higgs mass and Higgs pT (for now it is only for b quarks)
- muon ID (maybe not needed)
- embedding weight (? maybe not needed)
- some loose ID discriminators for electrons and muons (DepositR03Ecal,DepositR03TrackerOfficial,sigmaIetaIeta,deltaPhiSuperClusterTrackAtVtx, …)

**Comment by giacomoortona** [comment]
New list of requests from Cécile:
- number of PU for PU reweighting (maybe all variables for 3D reweighting?)
- booleans for each electron, muon and jet ID to make it easier than if everyone has to evaluate them based on many variables, in particular: Loose Muon, Medium Muon,  Tight Muon, cut based Loose Electron, cut based Medium Electron, cut based Tight Electron, cut based Veto Electron, non triggering Loose Electron, non triggering Tight Electron, triggering Loose Electron, triggering Tight Electron, jet ID Loose, jet ID Medium, jet ID Tight, pu jet ID Loose
- pu jet ID raw
- trigger objects with fired paths
- tau decay mode finding (usual and new ones)
- tau.zImpact()
- if tau.vertex().z() == goodVertices[0]
- other variables linked to the SV mass: pt, eta, phi, fittedMet().Rho()
- tau: chargedIsoPtSum, neutralIsoPtSum, puCorrPtSum
- reconstructed charge
- all tau ID discriminators (all anti ele, anti mu, …)

**Comment by l-cadamuro** [comment]
Many are in common to those listed here, some details are described (HTauTau sync):
https://twiki.cern.ch/twiki/bin/viewauth/CMS/HiggsToTauTauWorking2015
For the tau we can save all the recommended POG IDs:
https://twiki.cern.ch/twiki/bin/view/CMS/TauIDRecommendation13TeV
